# Inlude Salsa-CI as a base
include:
 - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
 - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml

variables:
  RELEASE: 'stretch-backports'
  SALSA_CI_DISABLE_VERSION_BUMP: 1
  SALSA_CI_DISABLE_REPROTEST: 1

stages:
  - build
  - test # Stage referenced by Salsa-CI template reprotest stanza, so must exist
  - publish # Stage referenced by Salsa-CI template aptly stanza, so must exist even though not used
  - upgrade in stretch-backports
  - upgrade from Stretch/Jessie

# In addition to Salsa-CI, also run these fully Galera specific build jobs
galera-4.x to galera-4.y upgrade:
  stage: upgrade in stretch-backports
  dependencies:
    - build
  image: debian:stretch-backports
  artifacts:
    when: always
    name: "$CI_BUILD_NAME"
    paths:
      - ${WORKING_DIR}/debug
  script:
    - sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d # Enable automatic restarts from maint scripts
    - cd ${WORKING_DIR} # Don't repeat this step, it's just cd ./debian/output
    - apt-get update
    # Install everything currently in stretch-backports
    - apt-get install -y galera-4 galera-arbitrator-4
    # Verify installation of Galera from stretch-backports
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
    # Install Galera built in this commit
    - apt-get install -y ./*.deb
    # Verify installation of Galera built in this commit
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
  variables:
      GIT_STRATEGY: none
  except:
    variables:
      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
  allow_failure: true # galera-4 does not exist in stretch-backports yet

galera-3 stretch to galera-4 upgrade:
  stage: upgrade from Stretch/Jessie
  dependencies:
    - build
  image: debian:stretch
  artifacts:
    when: always
    name: "$CI_BUILD_NAME"
    paths:
      - ${WORKING_DIR}/debug
  script:
    - sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d # Enable automatic restarts from maint scripts
    - cd ${WORKING_DIR} # Don't repeat this step, it's just cd ./debian/output
    - apt-get update
    # Install almost everything currently in Debian Stretch
    - apt-get install -y 'galera-*'
    # Verify installation of Galera from Stretch
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
    # Install Galera built in this commit
    - apt-get install -y ./*.deb
    # Verify installation of Galera built in this commit
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
  variables:
      GIT_STRATEGY: none
  except:
    variables:
      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/

galera-3 jessie to galera-4 upgrade:
  stage: upgrade from Stretch/Jessie
  dependencies:
    - build
  image: debian:jessie
  artifacts:
    when: always
    name: "$CI_BUILD_NAME"
    paths:
      - ${WORKING_DIR}/debug
  script:
    - sed -i "s/101/0/g" -i /usr/sbin/policy-rc.d # Enable automatic restarts from maint scripts
    - cd ${WORKING_DIR} # Don't repeat this step, it's just cd ./debian/output
    - apt-get update
    # Install almost everything currently in Debian Stretch
    - apt-get install -y 'galera-*'
    # Verify installation of Galera from Stretch
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
    # Install Galera built in this commit
    - sed 's/jessie/stretch/g' -i /etc/apt/sources.list # Enable next Debian release
    - apt-get update; apt-get install -y apt # Upgrade minimal stack first
    - apt-get install -y ./*.deb
    # Verify installation of Galera built in this commit
    - dpkg -l | grep -iE 'maria|mysql|galera' || true # List installed
  variables:
      GIT_STRATEGY: none
  except:
    variables:
      - $CI_COMMIT_TAG != null && $SALSA_CI_ENABLE_PIPELINE_ON_TAGS !~ /^(1|yes|true)$/
